# Generated by Django 5.2.1 on 2025-06-02 20:26

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UK', 'Универсальная'), ('OPK', 'Общепрофессиональная'), ('PK', 'Профессиональная')], max_length=3, verbose_name='Тип компетенции')),
                ('code', models.CharField(max_length=20, verbose_name='Код компетенции')),
                ('description', models.TextField(verbose_name='Описание компетенции')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Полное название факультета')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код профессионального стандарта')),
                ('title', models.CharField(max_length=255, verbose_name='Название стандарта')),
                ('domain', models.CharField(max_length=255, verbose_name='Сфера деятельности')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер приказа утверждения')),
                ('order_date', models.DateField(verbose_name='Дата утверждения')),
            ],
            options={
                'verbose_name': 'Профессиональный стандарт',
                'verbose_name_plural': 'Профессиональные стандарты',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Полное наименование вуза')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Сокращённое название')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('website', models.URLField(verbose_name='Ссылка на официальный сайт')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код дисциплины')),
                ('name', models.CharField(max_length=255, verbose_name='Название дисциплины')),
                ('competencies', models.ManyToManyField(to='edu_programs.competency', verbose_name='Компетенции')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код направления подготовки')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название направления подготовки')),
                ('profile', models.TextField(blank=True, verbose_name='Профиль образовательной программы')),
                ('approval_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Год утверждения')),
                ('qualification', models.CharField(blank=True, max_length=100, verbose_name='Присваиваемая квалификация')),
                ('duration_years', models.IntegerField(blank=True, null=True, verbose_name='Срок обучения в годах')),
                ('total_credits', models.IntegerField(blank=True, null=True, verbose_name='Общее количество зачётных единиц')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='Язык обучения')),
                ('contact_hours_min', models.IntegerField(blank=True, null=True, verbose_name='Минимальный объём контактной работы (в часах)')),
                ('document', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='uploads/opop/'), upload_to='opop_documents/', verbose_name='Файл документа ОПОП')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('processing_error', models.TextField(blank=True, null=True, verbose_name='Ошибка обработки')),
                ('disciplines', models.ManyToManyField(blank=True, to='edu_programs.discipline', verbose_name='Дисциплины')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_programs.faculty', verbose_name='Факультет')),
                ('professional_standards', models.ManyToManyField(blank=True, to='edu_programs.professionalstandard', verbose_name='Профессиональные стандарты')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_programs.university', verbose_name='ВУЗ')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_programs.university', verbose_name='ВУЗ'),
        ),
    ]
