# Generated by Django 5.2.1 on 2025-06-02 23:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='uploads/opop/'), unique=True, upload_to='opop_documents/', verbose_name='Файл документа ОПОП'),
        ),
    ]
